'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace WebApplication1


	Partial Public Class _Default

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' btnShowPopup control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnShowPopup As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' grid control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected grid As Global.DevExpress.Web.ASPxGridView.ASPxGridView

		''' <summary>
		''' popup control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected popup As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

		''' <summary>
		''' checkBoxList control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected checkBoxList As Global.System.Web.UI.WebControls.CheckBoxList

		''' <summary>
		''' btnShowInGrid control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnShowInGrid As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' SqlDataSource1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource
	End Class
End Namespace
